<?php

/**
 * @file
 * A module to display Google+ profile pictures of node authors in Google search results.
 *
 * This module adds a field to the user entity for a link the the user's Google+ profile.
 * Using that field, if it is filled, this module alters the By line of a node's full
 * content display to link to the Google+ profile. Finally, by setting "rel='author'"
 * Google will recognize and display an authors profile picture in its search results.
 */

/**
 * Implements template_preprocess_username()
 *
 * Alters the 'name' variable to be a link to a Google+ profile and set the
 * "rel='author'" attribute.
 */
function google_authorship_preprocess_username(&$variables) {

  $bundle = arg(0);
  $nid = arg(1);

  // if the content being displayed is a node and the username being
  // processed is not a commenter and is related to a node and that node is
  // being displayed currently.
  if ($bundle == 'node' && !array_key_exists('comment_body',
      $variables['account']) && array_key_exists('nid',
      $variables['account']) && $variables['account']->nid == $nid) {

    // Get the Google+ ID of the node authot if it exists.
    $google_id = google_authorship_get_google_id($variables['uid']);

    // If the ID exists then proceed, otherwise do nothing.
    if ($google_id !== NULL) {
      // then alter the link path.
      $variables['link_path'] = 'http://plus.google.com/' . $google_id;
      // and set rel="author" in the html output.
      $variables['link_attributes']['rel'] = 'author';
    }
  };
}

/**
 * Implements google_authorship_get_google_id()
 *
 * Returns a string containing the Google+ ID for a specified UID
 *
 * @param:
 * $uid: The user id of the node author
 *
 * @return:
 * A string with the Google+ ID of the node author, if it has been set or
 * NULL if it hasn't
 */
function google_authorship_get_google_id($uid) {

  // Loads the author's user account.
  $account = user_load($uid);

  // If the Google+ ID field is not empty then proceed.
  if (!empty($account->field_google_plus_id)) {

    // Get the Google+ ID.
    $google_id = $account->field_google_plus_id['und'][0]['safe_value'];
  }
  else {
    // If the Google+ ID field was empty, set $google_id to NULL.
    $google_id = NULL;
  };

  // Return the Google+ ID if it existed and was a valid length,
  // otherwise this will return NULL
  return $google_id;
}

/**
 * Implements hook_form_alter()
 *
 * Adds additional validation to the user profile edit form.
 */
function google_authorship_form_user_profile_form_alter(&$form,
                                                        &$form_state,
                                                        $form_id) {

  $form['#validate'][] = 'google_authorship_form_validate';
}

/**
 * Implements hook_form_validate()
 *
 * Verifies that the Google+ ID entered is a 21 digit numeric string.
 */
function google_authorship_form_validate(&$form, &$form_state) {

  // If the user input data into field_google_plus_id.
  if (!empty($form_state['values']['field_google_plus_id']['und'][0]['value'])) {

    // Get the form input for Google+ ID.
    $google_id = $form_state['values']['field_google_plus_id']['und'][0]['value'];

    // If the string is not 21 digits or it is not a numeric string.
    if(strlen($google_id) != 21 || !preg_match('/^\d+$/', $google_id)) {

      // Return for resubmission and display error.
      form_error($form, t('The Google+ ID should be 21 numeric digits.'));
    };
  };
}